import pandas as pd
pd.set_option('display.max_columns', None)

df = pd.read_excel('csk1.xlsx')
print(df)
print('---------------------------------------------')
print(df.isna())
print('---------------------------------------------')
print(df.notna())
print('---------------------------------------------')
print(df['ID'].drop_duplicates(), '\n\n', df)
print('---------------------------------------------')
print(df.dropna(how='all'))
print('---------------------------------------------')
print(df.fillna(value='Not Defined'))
print('---------------------------------------------')
print(df.replace({'Sam':'Mohit'}))
print('---------------------------------------------')
print(df)